// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SucculentCommunity.Data;

#nullable disable

namespace SucculentCommunity.Migrations
{
    [DbContext(typeof(SucculentContext))]
    [Migration("20260317072452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SucculentCommunity.Models.Announcement", b =>
                {
                    b.Property<long>("AnnounceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnnounceID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnnounceID");

                    b.ToTable("Announcement");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Comment", b =>
                {
                    b.Property<long>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentID"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CommentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.HasKey("CommentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PostID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Favorite", b =>
                {
                    b.Property<long>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FavoriteID"));

                    b.Property<string>("FavType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.Property<long?>("PostID")
                        .HasColumnType("bigint");

                    b.Property<string>("SpeciesID")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.HasKey("FavoriteID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PostID");

                    b.HasIndex("SpeciesID");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Member", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)");

                    b.HasKey("MemberID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Plant", b =>
                {
                    b.Property<long>("PlantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlantID"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.Property<string>("PlantImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlantNickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpeciesID")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.HasKey("PlantID");

                    b.HasIndex("MemberID");

                    b.HasIndex("SpeciesID");

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Post", b =>
                {
                    b.Property<long>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostID"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsPinned")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)");

                    b.Property<string>("IsPublic")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.Property<long?>("PlantID")
                        .HasColumnType("bigint");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)");

                    b.HasKey("PostID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PlantID");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("SucculentCommunity.Models.PostLike", b =>
                {
                    b.Property<long>("PostLikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostLikeID"));

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.HasKey("PostLikeID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PostID");

                    b.ToTable("PostLike");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Species", b =>
                {
                    b.Property<string>("SpeciesID")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Genus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GrowthSeason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LightGuide")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoilMix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpeciesImg")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WaterGuide")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SpeciesID");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Comment", b =>
                {
                    b.HasOne("SucculentCommunity.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SucculentCommunity.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Favorite", b =>
                {
                    b.HasOne("SucculentCommunity.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SucculentCommunity.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID");

                    b.HasOne("SucculentCommunity.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesID");

                    b.Navigation("Member");

                    b.Navigation("Post");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Plant", b =>
                {
                    b.HasOne("SucculentCommunity.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SucculentCommunity.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesID");

                    b.Navigation("Member");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("SucculentCommunity.Models.Post", b =>
                {
                    b.HasOne("SucculentCommunity.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SucculentCommunity.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantID");

                    b.Navigation("Member");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SucculentCommunity.Models.PostLike", b =>
                {
                    b.HasOne("SucculentCommunity.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SucculentCommunity.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
